<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

    <!-- Single-file build settings -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier> <!-- or win-x86 if needed -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed> <!-- set true if you want trimming (optional) -->
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <PackageIcon>New Projeckk.png</PackageIcon>
    <ApplicationIcon>timer.ico</ApplicationIcon> <!-- compress inside exe -->
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="Resources\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="Resources\**" />
    <None Remove="bin\**" />
    <None Remove="Resources\**" />
    <Page Remove="bin\**" />
    <Page Remove="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="41Lpjckklk1h8L.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\OneDrive\Изображения\New Projeckk.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resource1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource1.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.6" />
  </ItemGroup>

</Project>
